---
- name: Ensure basic prerequisites are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - python3-venv
    state: present
    update_cache: yes
